/* Generated By:JavaCC: Do not edit this line. CsparqlParserConstants.java */
package eu.larkc.csparql.core.new_parser ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CsparqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PREFIX = 5;
  /** RegularExpression Id. */
  int BASE = 6;
  /** RegularExpression Id. */
  int SELECT = 7;
  /** RegularExpression Id. */
  int DESCRIBE = 8;
  /** RegularExpression Id. */
  int ADD = 9;
  /** RegularExpression Id. */
  int ASK = 10;
  /** RegularExpression Id. */
  int CONSTRUCT = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int WHERE = 13;
  /** RegularExpression Id. */
  int SINGLELETTERTEXT = 14;
  /** RegularExpression Id. */
  int NUMBERS = 15;
  /** RegularExpression Id. */
  int SYMBOL = 16;
  /** RegularExpression Id. */
  int IRIref = 17;
  /** RegularExpression Id. */
  int SPACE = 18;
  /** RegularExpression Id. */
  int REGISTERSTREAM = 19;
  /** RegularExpression Id. */
  int REGISTERQUERY = 20;
  /** RegularExpression Id. */
  int STREAM = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int NAMED = 23;
  /** RegularExpression Id. */
  int RANGE = 24;
  /** RegularExpression Id. */
  int STEP = 25;
  /** RegularExpression Id. */
  int TUMBLING = 26;
  /** RegularExpression Id. */
  int TRIPLES = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"prefix \"",
    "\"base \"",
    "\"select \"",
    "\"describe \"",
    "\"add \"",
    "\"ask \"",
    "\"construct \"",
    "\" from \"",
    "\"where {\"",
    "<SINGLELETTERTEXT>",
    "<NUMBERS>",
    "<SYMBOL>",
    "<IRIref>",
    "\" \"",
    "\"register stream \"",
    "\"register query \"",
    "\"stream \"",
    "\"as \"",
    "\"named \"",
    "\"[range \"",
    "\"step \"",
    "\"tumbling \"",
    "\"triples \"",
  };

}
